activation: nn.ReLU()
anchors: 3
backbone:
- - -1
  - 1
  - Silence
  - []
- - -1
  - 1
  - Conv
  - - 64
    - 3
    - 2
- - -1
  - 1
  - Conv
  - - 128
    - 3
    - 2
- - -1
  - 1
  - RepNCSPELAN4
  - - 256
    - 128
    - 64
    - 1
- - -1
  - 1
  - Conv
  - - 256
    - 3
    - 2
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 256
    - 128
    - 1
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 512
    - 256
    - 1
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 512
    - 256
    - 1
depth_multiple: 1.0
head:
- - -1
  - 1
  - SPPELAN
  - - 512
    - 256
- - -1
  - 1
  - nn.Upsample
  - - null
    - 2
    - nearest
- - - -1
    - 7
  - 1
  - Concat
  - - 1
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 512
    - 256
    - 1
- - -1
  - 1
  - nn.Upsample
  - - null
    - 2
    - nearest
- - - -1
    - 5
  - 1
  - Concat
  - - 1
- - -1
  - 1
  - RepNCSPELAN4
  - - 256
    - 256
    - 128
    - 1
- - -1
  - 1
  - Conv
  - - 256
    - 3
    - 2
- - - -1
    - 13
  - 1
  - Concat
  - - 1
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 512
    - 256
    - 1
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - - -1
    - 10
  - 1
  - Concat
  - - 1
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 512
    - 256
    - 1
- - 5
  - 1
  - CBLinear
  - - - 256
- - 7
  - 1
  - CBLinear
  - - - 256
      - 512
- - 9
  - 1
  - CBLinear
  - - - 256
      - 512
      - 512
- - 0
  - 1
  - Conv
  - - 64
    - 3
    - 2
- - -1
  - 1
  - Conv
  - - 128
    - 3
    - 2
- - -1
  - 1
  - RepNCSPELAN4
  - - 256
    - 128
    - 64
    - 1
- - -1
  - 1
  - Conv
  - - 256
    - 3
    - 2
- - - 23
    - 24
    - 25
    - -1
  - 1
  - CBFuse
  - - - 0
      - 0
      - 0
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 256
    - 128
    - 1
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - - 24
    - 25
    - -1
  - 1
  - CBFuse
  - - - 1
      - 1
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 512
    - 256
    - 1
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - - 25
    - -1
  - 1
  - CBFuse
  - - - 2
- - -1
  - 1
  - RepNCSPELAN4
  - - 512
    - 512
    - 256
    - 1
- - - 31
    - 34
    - 37
    - 16
    - 19
    - 22
  - 1
  - DualDDetect
  - - nc
names:
- boneanomaly
- bonelesion
- foreignbody
- fracture
- metal
- periostealreaction
- pronatorsign
- softtissue
- text
nc: 9
width_multiple: 1.0
